// Generated by CoffeeScript 1.10.0
(function() {
  var app, cart, express, klarna, server;

  express = require("express");

  klarna = require('./../src/klarna');

  klarna.init({
    eid: '',
    secret: '',
    test: true
  });

  klarna.config({
    terms_uri: 'http://www.example.com',
    cancellation_terms_uri: 'http://www.example.com',
    checkout_uri: 'http://www.example.com',
    confirmation_uri: 'http://www.example.com',
    push_uri: 'http://www.example.com'
  });

  cart = {
    items: [
      {
        name: 'Spam',
        reference: '1234',
        quantity: 1,
        unit_price: 3400,
        tax_rate: 2500
      }
    ]
  };

  app = express();

  app.set('view-options', {
    pretty: true
  });

  app.get('/', function(req, res) {
    return klarna.place(cart).then(function(id) {
      return klarna.fetch(id);
    }, function(error) {
      return res.send(error);
    }).then(function(order) {
      var html;
      html = '<div style="text-align: center; font-family: Helvetica, sans-serif">' + 'Order id: ' + order.id + '<br><br>' + 'Open <a href="localhost:3000/' + order.id + '">this link</a> in another browser tab and reload the page when you have completed your checkout to confirm your purchase.' + order.gui.snippet;
      return res.send(html);
    }, function(error) {
      return res.send(error);
    });
  });

  app.get('/:id', function(req, res) {
    var klarnaId, myId;
    if (req.params.id != null) {
      klarnaId = req.params.id;
      myId = 'my_ref_01';
      return klarna.confirm(klarnaId, myId).then(function(order) {
        return res.send(order.gui.snippet);
      }, function(error) {
        return res.send(error);
      });
    }
  });

  server = app.listen(3000, function() {
    var host, port;
    host = server.address().address;
    port = server.address().port;
    console.log('Klarna Test Server running at http://%s:%s', host, port);
    return console.log('Enter address above in browser to make a test purchase', host, port);
  });

}).call(this);
