// Generated by CoffeeScript 1.10.0
(function() {
  var fs, prompt, run, schemas;

  prompt = require("prompt");

  fs = require("fs");

  schemas = {
    input: {
      properties: {
        eid: {
          required: true,
          message: '\n  Merchant id (eid):'.white
        },
        secret: {
          required: true,
          message: '  Shared secret:'.white
        }
      }
    },
    confirmation: {
      properties: {
        confirmation: {
          required: true,
          "default": 'yes',
          message: '\nIs this correct, yes/no?'.white
        }
      }
    }
  };

  prompt.message = '';

  prompt.delimiter = '';

  console.log("\nSetting up Klarna Checkout example server".green);

  prompt.start();

  run = function() {
    return prompt.get(schemas.input, function(err, result) {
      var credentials;
      credentials = {
        eid: result.eid,
        secret: result.secret
      };
      console.log("\nYou entered:".green);
      console.log(("\n  eid: " + result.eid).white);
      console.log(("  secret: " + result.secret).white);
      return prompt.get(schemas.confirmation, function(err, result) {
        if (result.confirmation === 'no') {
          return run();
        } else {
          fs.writeFileSync('credentials.json', JSON.stringify(credentials));
          return console.log("\nSetup complete!\n".green);
        }
      });
    });
  };

  run();

}).call(this);
